name: Update Swagger UI
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  updateSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest Swagger UI Release
        id: gpt4free
      - uses: actions/checkout@v4
        with:
          repository: 'xtekky/gpt4free'
          path: 'g4f'
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: 'pip'
      - name: Install requirements
        run: |
          pip install fastapi uvicorn python-multipart
          pip install -r requirements-min.txt
      - name: Generate openapi.json
        run: |
          python -m g4f.etc.tool.openapi
      - name: Update Swagger UI
        run: |
          # Delete the dist directory and index.html
          rm -fr dist index.html
          # Download the release
          release_tag=$(curl -sL https://api.github.com/repos/swagger-api/swagger-ui/releases/latest | jq -r ".tag_name")
          curl -sL -o $release_tag https://api.github.com/repos/swagger-api/swagger-ui/tarball/$release_tag
          # Extract the dist directory
          tar -xzf $release_tag --strip-components=1 $(tar -tzf $release_tag | head -1 | cut -f1 -d"/")/dist
          rm $release_tag
          # Move index.html to the root
          mv dist/index.html .
          # Fix references in dist/swagger-initializer and index.html
          sed -i "s|https://petstore.swagger.io/v2/swagger.json|swagger.yml|g" dist/swagger-initializer.js
          sed -i "s|href=\"./|href=\"dist/|g" index.html
          sed -i "s|src=\"./|src=\"dist/|g" index.html
          sed -i "s|href=\"index|href=\"dist/index|g" index.html
          # Update current release
          echo ${{ steps.gpt4free.outputs.release_tag }} > gpt4free.version
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update swagger-ui to ${{ steps.gpt4free.outputs.release_tag }}
          title: Update SwaggerUI to ${{ steps.gpt4free.outputs.release_tag }}
          body: |
            Updates [gpt4free] to ${{ steps.gpt4free.outputs.release_tag }}

            Auto-generated by [create-pull-request]
          labels: dependencies, automated pr
          branch: gpt4free-updates
